name: "Build and push Super Mario Docker image with static and latest tags to Docker Hub"

on:
    push:
        branches:
            - main

jobs:
    build_push_supermario_docker_image:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            - name: Build and Push Docker Image
              run: |
                  IMAGE_NAME=kavinduorg/supermariogitopsproject
                  GIT_SHA=${{ github.sha }}

                  # Build image with both tags
                  docker build -t $IMAGE_NAME:$GIT_SHA -t $IMAGE_NAME:latest .

                  # Push both tags
                  docker push $IMAGE_NAME:$GIT_SHA
                  docker push $IMAGE_NAME:latest
