name: "SAST Scan, Build/Push SuperMario Docker Image, and Update K8s Deployment"

on:
    push:
        branches:
            - main

jobs:
    sonarqube_sast_scan:
        name: Run SAST Scan
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # Needed for accurate Sonar analysis

            - name: SonarQube Scan
              uses: sonarsource/sonarqube-scan-action@master
              env:
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    build_push_supermario_docker_image:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        needs: sonarqube_sast_scan # Run only after successful SAST scan

        outputs:
            image_tag: ${{ steps.set_output.outputs.image_tag }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            - name: Build and Push Docker Image
              id: set_output
              run: |
                  IMAGE_NAME=kavinduorg/supermariogitopsproject
                  GIT_SHA=${{ github.sha }}

                  # Build image with both tags
                  docker build -t $IMAGE_NAME:$GIT_SHA -t $IMAGE_NAME:latest .

                  # Push both tags
                  docker push $IMAGE_NAME:$GIT_SHA
                  docker push $IMAGE_NAME:latest

                  # Export Git SHA as output for next job
                  echo "image_tag=$GIT_SHA" >> $GITHUB_OUTPUT

    update_k8s_yaml_version_file_with_latest_image_tag:
        name: Update K8s Deployment YAML with Latest Image Tag
        runs-on: ubuntu-latest
        needs: build_push_supermario_docker_image

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Set Git Config
              run: |
                  git config --global user.email "${{ secrets.GIT_EMAIL }}"
                  git config --global user.name "${{ secrets.GIT_USERNAME }}"

            - name: Update Deployment YAML
              env:
                  VERSION: ${{ needs.build_push_supermario_docker_image.outputs.image_tag }}
              run: |
                  git pull
                  # Update image tag in deployment.yaml
                  sed -i "s|image: kavinduorg/supermariogitopsproject:.*$|image: kavinduorg/supermariogitopsproject:${VERSION}|" deployment.yaml



                  git commit -m "Updated deployment.yaml  with SuperMario image tag ${VERSION}"
                  git push
