name: "SAST Scan and Build/Push SuperMario Docker Image"

on:
    push:
        branches:
            - main

jobs:
    sonarqube_sast_scan:
        name: Run SAST Scan
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # Needed for accurate Sonar analysis

            - name: SonarQube Scan
              uses: sonarsource/sonarqube-scan-action@master
              env:
                  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    build_push_supermario_docker_image:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        needs: sonarqube_sast_scan # Run only after successful SAST scan

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Login to Docker Hub
              run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            - name: Build and Push Docker Image
              run: |
                  IMAGE_NAME=kavinduorg/supermariogitopsproject
                  GIT_SHA=${{ github.sha }}

                  # Build image with both tags
                  docker build -t $IMAGE_NAME:$GIT_SHA -t $IMAGE_NAME:latest .

                  # Push both tags
                  docker push $IMAGE_NAME:$GIT_SHA
                  docker push $IMAGE_NAME:latest
